name: Run Tests in the project every push on GitHub

on: [push, pull_request]

jobs:
  build: 
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd server
      - run: npm install
      - name: Link
        run: npm run linter
      - name: Test
        run: npm test
